name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'        # Angular needs ≥20.19

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production
        # this produces dist/synonyms-app/browser/index.html

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_TREE_017AF5003 }}
          repo_token:                            ${{ secrets.GITHUB_TOKEN }}
          action:                                upload
          app_location:                          "/"                             # your source root
          output_location:                       "dist/synonyms-app/browser"     # where index.html actually is
          skip_app_build:                        true                            # ⬅️ don’t let Oryx rebuild :contentReference[oaicite:0]{index=0}
          skip_api_build:                        true                            # ⬅️ only if you have no Azure Functions :contentReference[oaicite:1]{index=1}





